<?php

namespace TicketingUserBundle\Repository;

/**
 * UtilisateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll()

    {

        $qb = $this->createQueryBuilder('u');




        return $qb
            ->orderBy('u.nom')

            ->getQuery()

            ->getResult()

            ;

    }
}
