# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\Utilisateurs: plaintext
    TicketingUserBundle\Entity\Utilisateurs: plaintext

  role_hierarchy:
    ROLE_USER:       [ROLE_DEM]
    ROLE_TECH:       [ROLE_RAPP]
    ROLE_ADMIN:       [ROLE_TRIE]
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:

          entity:

            class:    TicketingUserBundle\Entity\Utilisateurs

            property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
        pattern: ^/
        anonymous: true
        provider: main
        form_login:
            login_path: login
            check_path: login_check
            always_use_default_target_path: true
            default_target_path: /Ticketing
        logout:
            path: logout
            target: login

  access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }
