ticketing_homepage:
    path:     /Ticketing
    defaults: { _controller: TicketingBundle:Ticketing:index }

ticketing_user:
    path:     /Ticketing/user
    defaults: { _controller: TicketingBundle:Ticketing:user }


ticketing_tech:
    path:     /Ticketing/tech
    defaults: { _controller: TicketingBundle:Ticketing:tech }

ticketing_admin:
    path:     /Ticketing/admin
    defaults: { _controller: TicketingBundle:Ticketing:admin }

checking_role:
    path:     /Ticketing
    defaults: { _controller: TicketingBundle:Ticketing:index }

ticketing_add:
    path:     /Ticketing/user/add
    defaults: { _controller: TicketingBundle:Ticketing:add }

demande_view:

    path:      /Ticketing/user/{page}

    defaults:

        _controller: TicketingBundle:Ticketing:view


    requirements:

        id: \d+

demandes_view:

    path:      /Ticketing/admin/demandes

    defaults:

        _controller: TicketingBundle:Ticketing:demandes


    requirements:

        id: \d+

ticketing_attribute:
    path:     /Ticketing/admin/attribute/{page}
    defaults: { _controller: TicketingBundle:Ticketing:attribute }

ticketing_resolve:
    path:     /Ticketing/tech/resolve/{page}
    defaults: { _controller: TicketingBundle:Ticketing:resolve }

ticketing_inscription:
    path:     /Ticketing/inscription
    defaults: { _controller: TicketingBundle:Ticketing:inscription }

ticketing_inscription_tech:
    path:     /Ticketing/admin/inscription
    defaults: { _controller: TicketingBundle:Ticketing:inscriptiontech }